# Generated by Django 4.1.3 on 2022-11-26 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ename', models.CharField(max_length=60)),
                ('eid', models.IntegerField()),
                ('edes', models.TextField()),
                ('edate', models.IntegerField()),
                ('edept', models.TextField()),
                ('esal', models.FloatField()),
                ('eexp', models.IntegerField()),
            ],
        ),
    ]
