# Generated by Django 4.1.3 on 2022-11-28 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app7', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noccation', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='employee',
            name='edate',
            field=models.FloatField(),
        ),
    ]
