# Generated by Django 4.1.3 on 2022-11-28 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app7', '0002_news_alter_employee_edate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holidays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('occation', models.TextField()),
            ],
        ),
    ]
