# Generated by Django 4.1.3 on 2022-11-29 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app7', '0003_holidays'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='edate',
            field=models.DateField(),
        ),
    ]
